apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: yarn-prometheus-data
  annotations:
    volume.beta.kubernetes.io/storage-class: "managed-nfs-storage"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi