apiVersion: v1
kind: Service
metadata:
  name: yarn-exporter-svc
  labels:
    app: yarn-exporter
spec:
  type: NodePort
  ports:
  - port: 9113
    nodePort: 30113
  selector:
    app: yarn-exporter
