apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-alerts
data:
  alertmanager.yml: |
    global:
      resolve_timeout: 5m

      smtp_smarthost: 'mailo2.uhc.com:25'
      smtp_from: 'AlertManager <example@optum.com>'
      smtp_require_tls: false

    route:
      receiver: 'default'

    receivers:
      - name: 'default'
        email_configs:
          - to: 'Alert Receiver <example@optum.com>'
            from: 'Alertmanager <example@optum.com>'
            send_resolved: true
